name: devfest_2018
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
#
# version:(バージョンネーム+バージョンコード) の運用規定
# １．iOS/Android ともに、App Store / Google Play 公開バージョンネームは 同一とする。
# ２．バージョンコードは、バージョンネームが上がる毎に、以前の値から +1 とする。
# ３．バージョンネームからバージョンコードを推定できるようにしません。
#   　つまり バージョンネームの <major>.<minor>.<point> の各桁数位置を指定しません。
#   　例えば、バージョンネームが "1.4.2" なら、2 + 4×10 + 1×100 ⇒ 142 とはしません。
# ４．(iOS) App Store 内部でのバージョンコードは、申請都合による任意値とします。
# ５．(Android) APK 内のバージョンコードは、バージョンコード × 10 + α とします。
# 　　(α には、32bit版:1、64bit版:2、ローカルビルド/DeployGate版:0 が指定されます)
#
# version: 左辺項目（例:1.0.0+1 の 1.0.0） ⇒ バージョンネーム
# ・ios/Flutter/Generated.xcconfig の FLUTTER_BUILD_NAME に同期され、
# 　ios/Runner/info.plist の CFBundleShortVersionString に適用されます。
# ・android/local.properties の flutter.versionName に同期され、
# 　android/app/build.gradle の versionName に適用されます。
#
# version: 右辺項目（例:1.0.0+1 の 1） ⇒ バージョンコード
# ・ios/Flutter/Generated.xcconfig の FLUTTER_BUILD_NUMBER に同期され、
# 　ios/Runner/info.plist の CFBundleVersion に適用されます。
# ・android/local.properties の flutter.versionCode に同期され、
# 　android/app/build.gradle の versionCode に適用されます。
version: 1.1.3+10023

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # DevFest 2018 サービスデモ用に追加
  google_sign_in: ^4.0.4
  firebase_auth: ^0.11.1+8
  cloud_firestore: ^0.12.7
  firebase_messaging: ^5.1.0
  firebase_storage: ^3.0.3
  image_picker: ^0.6.0+15


dev_dependencies:
  # Unitテストを追加
  test: '<3.0.0'

  # Widgetテストを追加
  flutter_test:
    sdk: flutter

  # iOS/Android アイコン生成ツール
  flutter_launcher_icons: "^0.6.1"

# iOS/Android アイコン生成ツール設定
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/devfest-kyoto-2018.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    # Sign-In Branding Guidelines のリソースより
    # https://developers.google.com/identity/branding-guidelines
    - assets/images/btn_google_signin_dark_normal_web_2x.png

